require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TodosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Todo. As you add validations to Todo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { txt: Faker::Lorem.sentence }
  }

  let(:invalid_attributes) {
    {
      txt: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TodosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all todos as @todos" do
      todo = Todo.create! valid_attributes
      get :index, {format: :json}, valid_session
      expect(assigns(:todos)).to eq([todo])
    end
  end

  describe "GET #show" do
    it "assigns the requested todo as @todo" do
      todo = Todo.create! valid_attributes
      get :show, {format: :json, :id => todo.to_param}, valid_session
      expect(assigns(:todo)).to eq(todo)
    end
  end

=begin
  describe "GET #new" do
    it "assigns a new todo as @todo" do
      get :new, {format: :json}, valid_session
      expect(assigns(:todo)).to be_a_new(Todo)
    end
  end

  describe "GET #edit" do
    it "assigns the requested todo as @todo" do
      todo = Todo.create! valid_attributes
      get :edit, {format: :json, :id => todo.to_param}, valid_session
      expect(assigns(:todo)).to eq(todo)
    end
  end
=end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Todo" do
        expect {
          post :create, {format: :json, :todo => valid_attributes}, valid_session
        }.to change(Todo, :count).by(1)
      end

      it "assigns a newly created todo as @todo" do
        post :create, {format: :json, :todo => valid_attributes}, valid_session
        expect(assigns(:todo)).to be_a(Todo)
        expect(assigns(:todo)).to be_persisted
      end

      it "redirects to the created todo" do
        post :create, {format: :json, :todo => valid_attributes}, valid_session
        expect(response).to have_http_status(:created)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved todo as @todo" do
        post :create, {format: :json, :todo => invalid_attributes}, valid_session
        expect(assigns(:todo)).to be_a_new(Todo)
      end

      it "re-renders the 'new' template" do
        post :create, {format: :json, :todo => invalid_attributes}, valid_session
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          done: true
        }
      }

      it "updates the requested todo" do
        todo = Todo.create! valid_attributes
        expect(todo.done).to be(false)
        put :update, {format: :json, :id => todo.to_param, :todo => new_attributes}, valid_session
        todo.reload
        expect(todo.done).to be(true)
      end

      it "assigns the requested todo as @todo" do
        todo = Todo.create! valid_attributes
        put :update, {format: :json, :id => todo.to_param, :todo => valid_attributes}, valid_session
        expect(assigns(:todo)).to eq(todo)
      end

      it "redirects to the todo" do
        todo = Todo.create! valid_attributes
        put :update, {format: :json, :id => todo.to_param, :todo => valid_attributes}, valid_session
        expect(response).to have_http_status(:success)
      end
    end

    context "with invalid params" do
      it "assigns the todo as @todo" do
        todo = Todo.create! valid_attributes
        put :update, {format: :json, :id => todo.to_param, :todo => invalid_attributes}, valid_session
        expect(assigns(:todo)).to eq(todo)
      end

      it "re-renders the 'edit' template" do
        todo = Todo.create! valid_attributes
        put :update, {format: :json, :id => todo.to_param, :todo => invalid_attributes}, valid_session
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested todo" do
      todo = Todo.create! valid_attributes
      expect {
        delete :destroy, {format: :json, :id => todo.to_param}, valid_session
      }.to change(Todo, :count).by(-1)
    end

    it "redirects to the todos list" do
      todo = Todo.create! valid_attributes
      delete :destroy, {format: :json, :id => todo.to_param}, valid_session
      expect(response).to have_http_status(:no_content)
    end
  end

end
